### ISSUE TITLE
run_chroot_local not matching build farm results on prerelease

### ISSUE THREAD

**Issue by rctoris** [ros-infrastructure/jenkins_scripts#35]
While trying to debug a problem with one of my projects on the build farm, I tried to run a prerelease test locally (the build was only failing on Oneiric). However, the local build would always pass and not match the failing build that was happening on the farm.

Here is the failing job (`rosauth` version 0.1.2): http://jenkins.willowgarage.com:8080/view/GbinO32/job/ros-groovy-rosauth_binarydeb_oneiric_i386/73/

By running ` run_chroot_local oneiric i386 /home/tor1pal/tmp prerelease groovy rosauth 0.1.2`, the build would pass and I uploaded the log from the run: http://pastebin.com/iHAucDTj

Sidenote: I managed to fix the failing build with `rosauth` version 0.1.3.

**Comment by tfoote** [comment]
We're switching to use Docker on the new build farm. The users will be able to run the exact builds using that system. Closing as won't fix for the existing infrastructure.
