### ISSUE TITLE
doc script: should run a stable, released version of rosdoc_lite

### ISSUE THREAD

**Issue by jack-oquin** [ros-infrastructure/jenkins_scripts#47]
The Jenkins `doc` script currently checks out the latest development branch of `rosdoc_lite` when building wiki documentation.

That makes it unnecessarily difficult to do development work on `rosdoc_lite`, because any commit may cause documentation jobs to start failing. Worse, `rosdoc_lite` currently has no unit test cases. 

I am open to suggestions for how the `doc` script should best access `rosdoc_lite`. It is currently released as per-distro Ubuntu packages to both Groovy and Hydro (0.2.2) plus an earlier Fuerte release (0.1.3).

**Comment by dirk-thomas** [comment]
Since this is not going to be changed anymore for the existing buildfarm I will close this as "wontfix".
